server:
  port: 8084
base-url:
  context: /repos
app:
  host: localhost:8084

log:
  identifierKey: UUID
  isDebug: true
  isInfo: true

logging:
  request:
    shouldLogInfo: true
  response:
    shouldLogInfo: false
  level:
    root: debug

request:
  id-key: requestId

github-api:
  get-commit-list: https://api.github.com/repos/{{OWNER}}/{{CODE_REPO}}/commits
  get-issue-list: https://api.github.com/issues
  get-fork-list: https://api.github.com/repos/{{OWNER}}/{{CODE_REPO}}/forks
  get-pull-list: https://api.github.com/repos/{{OWNER}}/{{CODE_REPO}}/pulls
  Token: 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

#spring.datasource.url: jdbc:mysql://host.docker.internal:3306/iit_cc_cw?createDatabaseIfNotExist=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
spring.datasource.url: jdbc:mysql://aurora-cluster-iit-cc-cw.cluster-cgb3lemiktxz.us-west-2.rds.amazonaws.com/iit_cc_cw?createDatabaseIfNotExist=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
spring.datasource.password: "mypassword"
spring.datasource.username: myusername
#spring.datasource.url: jdbc:mysql://localhost:3306/iit_cc_cw?createDatabaseIfNotExist=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
#spring.datasource.password: "!Qaz2wSX"
#spring.datasource.username: root
spring.datasource.maxActive: 20
spring.datasource.maxIdle: 10
spring.datasource.maxWait: 10000
spring.jpa.generate-ddl: true
spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring.jpa.properties:
      hibernate:
        dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
hibernate:
  jdbc:
    time_zone: UTC